### ISSUE TITLE
新ネタでしてよ！

### ISSUE THREAD

**Issue by McCarroney** [HansRobo/CodeReviewLady#9]
「コードレビューお嬢様」に私が考えた最強の一文を提案いたしますわ．　　
ここに書きますから追加なさってくださいまし．
**「あらあら、Vimをお使いではありませんの？」**
それでは，ごきげんよう．

**Comment by HansRobo** [comment]
これはVimを使うかそうでないかは個人の自由ですわ．
それを一方的に押し付けることは良くないと思いますわ
